name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git ccache libffi-dev libssl-dev openjdk-17-jdk unzip tar wget
        pip install --upgrade pip
        pip install --upgrade buildozer "cython<3.0.0"

    - name: Build APK with Buildozer
      run: |
        buildozer init
        sed -i 's/title = My Application/title = AlDimashqi/g' buildozer.spec
        sed -i 's/package.name = myapp/package.name = aldimashqi/g' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.aldimashqi/g' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,ttf,db/g' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
        sed -i 's/# android.api = 31/android.api = 33/g' buildozer.spec
        sed -i 's/# android.minapi = 21/android.minapi = 24/g' buildozer.spec
        sed -i 's/android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a/g' buildozer.spec
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AlDimashqi-APK
        path: bin/*.apk
